[package]
name = "nominae"
edition = "2018"
version = "0.1.0"
authors = ["Hans W. Uhlig <huhlig@gmail.com>"]
description = "English Name Generation Library"

[dependencies.rand]
version = "0.8"
features = ["small_rng"]
